CD: #各种操作cd 必须为整数 单位：分
  association: 10080 #宗门维护
  joinassociation: 450 #退宗
  associationbattle: 1440 #宗门大战
  rob: 120 # 打劫CD
  gambling: 10 # 金银坊
  couple: 360 #双修
  garden: 3 # 药园
  level_up: 3 # 突破
  secretplace: 7 #秘境
  yijiesecretplace: 3 #异界秘境
  yijiplace: 12 #遗迹
  timeplace: 6 #仙府
  forbiddenarea: 4 #禁地
  reborn: 360 # 重生
  transfer: 360 # 转账
  honbao: 1 # 抢红包
  boss: 30 #boss
  bossSpawn: 43200000 #boss刷新

percentage:
  cost: 0.07 #手续费
  Moneynumber: 0.4 #金银坊收益
  punishment: 0.2 #出千收益

size:
  Money: 100 #单位：万，出千控制
mine: #挖矿最长时间：最低*周期
  size: 12 #挖矿倍率！收益：倍率*境界数*天赋*时间
  time: 30 #挖矿最低时间
  cycle: 48 #挖矿周期
switch: #开true 关false
  play: true #怡红院开关
  Moneynumber: true #金银坊开关
  couple: true #双修开关
  Xiuianplay_key: false #怡红院卡图开关

biguan: #闭关最长时间：最低*周期
  size: 9 #闭关倍率！收益：倍率*境界数*天赋*时间
  time: 30 #闭关最低时间
  cycle: 240 #闭关周期

work: #打工
  size: 15 #打工倍率！收益：倍率*境界数*时间
  time: 15 #打工最低时间
  cycle: 48 #打工周期

Boss:
  Boss: 1.4 #奖励倍率

Auction:
  interval: 1 #间歇时间
  openHour: 21 #星阁开启时间
  closeHour: 23 #星阁关闭时间

SecretPlace: #秘境出金概率
  one: 0.97 #0.97保底，0.03蚂蚁
  two: 0.6
  three: 0.2 #0.2出金，0.8小金

SudokuGame: # 数独游戏时间间隔
  time: 30

najie_num: # 纳戒存储量
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 5000000

najie_price: # 纳戒升级消耗 需要对应najie_num保持数据量一致
  - 0
  - 50000
  - 100000
  - 500000
  - 500000
  - 1000000
  - 3000000

Group: #推送群
  - 1111
